### ISSUE TITLE
Strange behaviour when loop option is true

### ISSUE THREAD

**Issue by snc** [nickpisacane/react-dynamic-swiper#10]
When setting `loop` to true, old state is used somehow.

I've created an example here:

[![Edit react-dynamic-swiper](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/38yjn3k8o6)

Navigate left once, you would expect to see "Slide 5" instead of "Loading...". Now navigating right once, you don't see "Slide 1" but instead "Loading...".

**Comment by nickpisacane** [comment]
Thanks for the sanbox link! Looks like the general approach to updating slides needs to change. The slides are being updated, but iDangerous is still hanging onto the clones before the update (iDangerous clones slides when `loop = true`). Will look into solutions.

**Comment by nickpisacane** [comment]
This is proving to be pretty perplexing. I've tried a couple of things: force updating the iDangerous Swiper, completely reinitializing the swiper, and removing the duplicates before re-initializing. None seem to work, and the former two are extremely problematic producing some pretty weird results. I'll keep looking for solutions, but help would be appreciated on this.

**Comment by loopmode** [comment]
Damn, I need just this - but of course the project schedule is ultra tight. I hope I can spend some time and see what's going on.

**Comment by nickpisacane** [comment]
This issue is definitely because of how looping works in iDangerous. An issue that gets at the core of this is open right now, so I am going to close this one. Please continue any conversation on this topic in #14

**Comment by nickpisacane** [comment]
Sorry for the hold up! I know this is closed, but just in case you all hadn't seen the comment on the other issue, loop mode will be supported in version 2! Please see #14 for more info
