### ISSUE TITLE
Trigger sliding to particular slide with onClick dilema

### ISSUE THREAD

**Issue by combustionspark** [nickpisacane/react-dynamic-swiper#12]
Hello.
I'm building a mobile web application, I have 4 slides, each has a React component as a child and 4 tabs as a navigation, I managed to make 
( swiping the slider => change the active tab ) 
... but struggle to make the opposite.
( clicking the tab => swipes the slider to the right slide ) ....

Opening the react dev tools in chrome and navigating to the Swiper component, there I see the props and all the states I  can have ... sadly I  don't understand how to use those states,  and also there is a
 `_slideTo: fn()` state which I  guess can work somehow

you can see the project  live here
https://combustionspark.github.io/app/

**Comment by nickpisacane** [comment]
Sorry for the late response. You can use `swiperRef.swiper().slideTo(slideIndex)` to programmatically change to a given slide. For reference, here are the docs on the iDangerous swiper (exposed as `swiperRef.swiper()`): [iDangerous Methods](http://idangero.us/swiper/api/#methods)
