### ISSUE TITLE
Clone element for loop not in React

### ISSUE THREAD

**Issue by williammanco** [nickpisacane/react-dynamic-swiper#14]
Hi guys,
the loop option in config use a native swiper functions to clone slide, but this create a problem with React components  because the cloned element is outside of react pattern, like a rendering or other events associated to a children component.

For example if I use an external component to child of **SlideItem**
`
<SlideItem>
   <MyComponent />
</SlideItem>
`

**Comment by nickpisacane** [comment]
Thanks for bringing this up, I will take a look at it.

**Comment by nickpisacane** [comment]
Closing this now as it has been fixed in version 2.0.0, current under the master branch now. 2.0.0-beta is available on NPM, but full release is coming very soon.
