### ISSUE TITLE
Could not find a declaration file for module 'react-dynamic-swiper'

### ISSUE THREAD

**Issue by reZach** [nickpisacane/react-dynamic-swiper#15]
Hello,

I have the following error (in the title) when importing the package into my .tsx file as shown below (as listed to do in the readme). Is there something I need to do?

`import { Swiper, Slide } from 'react-dynamic-swiper';`

**Comment by nickpisacane** [comment]
Sorry for the late reply. I am assuming that is a TypeScript generated error? Currently, there are no type declarations for TypeScript or Flow, but those are coming in the version 2 (the idangerous-v4-integration branch) is where a lot of that work is being done. As a TypeScript user myself, you can modify your configuration or provide your own declaration file for a quick fix. I would accept a pull request for a declaration file too, but beware some things are changing in version 2.0.0. Hope that helps!
