### ISSUE TITLE
swiper customization and slides content

### ISSUE THREAD

**Issue by mprevot** [nickpisacane/react-dynamic-swiper#17]
Hello,

- how do you recommend to used customization files for swiper ? (swiper.config.js and a css file)
- how do you put an image as a slide ?

I'm using this html code:
```
<div class="swiper-container" style="position: absolute">
	<div class="swiper-wrapper">
		<div class="swiper-slide diapo"><img src="images/im1.jpg" class="shadowed" /></div>
		<div class="swiper-slide diapo"><img src="images/im2.jpg" class="shadowed" /></div>
		<div class="swiper-slide diapo last"><img src="images/im3.jpg" class="shadowed" /></div>
		<div class="swiper-pagination"></div>
	</div>
</div>
```

I think this deserves a little development in the README.
Thanks.

**Comment by nickpisacane** [comment]
From the looks of it, you are looking for [iDangerous](http://idangero.us/swiper/). This is a [React](https://reactjs.org/) wrapper around that. If not, the `Slide` component can take any `ReactNode` as a children, i.e. an image.
