### ISSUE TITLE
Activate a slide on init that isn't the first slide.

### ISSUE THREAD

**Issue by jalite1991** [nickpisacane/react-dynamic-swiper#21]
I need to be able to update which slide the swiper initializes with. I was wondering if we could pass in a prop that updates which slide we are on.

**Comment by pleopardi** [comment]
It's possible with the `onInitSwiper` prop.

For example: 
`onInitSwiper={handleInitSwiper}` 
with 
`handleInitSwiper = swiper => swiper.slideTo(initialSlideIndex);`

**Comment by nickpisacane** [comment]
@jalite1991 Sorry for the late reply, and @pleopardi thanks for your answer - definitely what I would recommend as well.
