### ISSUE TITLE
Slide child mounted before style applied

### ISSUE THREAD

**Issue by jbreemhaar** [nickpisacane/react-dynamic-swiper#22]
Hi,

It seems that the <Slide> child is mounted before style (width) is applied to the <Slide>. Im my usecase I need to get the dimensions of the child, but on mount it's the full width of the parent container, which makes me think mounting takes place before the style. 

I've looked at your docs, and the iDangerous docs, but couldn't find any event or way to fix my problem. Do you have any idea?

**Comment by nickpisacane** [comment]
Sorry for the delay on this. Will look into this

**Comment by nickpisacane** [comment]
Do you by chance have a reproducible example?
