### ISSUE TITLE
change direction on resize

### ISSUE THREAD

**Issue by dirkschmid** [nickpisacane/react-dynamic-swiper#24]
Hey guys,

I want to change the direction of the slider on resize of the `window`, but I don't know how to access the slider, currently, I only got it working on init:
`<Swiper swiperOptions={params} onInitSwiper={handleInitSwiper}>`

```
  const handleInitSwiper = swiper => {
      this.state.width < 768 ? swiper.changeDirection('vertical') : swiper.changeDirection('horizontal')
    }
```

Has anyone an idea?

**Comment by nickpisacane** [comment]
@dirkschmid Sorry for the delay. You can also access the swiper instance imperatively via a ref. Here's an example:

```js
<Swper ref={swiper => { this.swiperRef = swiper} />
// Some where in your code
const swiper = this.swiperRef.swiper();
this.state.width < 768 
   ? this.swiperRef.swiper().changeDirection('vertical')
    : this.swiperRef.swiper().changeDirection('horizontal');
```

As a note, you won't want to cache the swiper instance as it is sometimes destroyed and swapped out by react-dynamic-swiper. The swiper() method will always give you the current instance.
