### ISSUE TITLE
clickable option in pagination is not working

### ISSUE THREAD

**Issue by raerpo** [nickpisacane/react-dynamic-swiper#25]
Hi,

iDangerous swiper has an option to make the pagination bullets clickable but in react-dynamic-swiper is not working. I search for it in the documentation and even running it in the demo application but it didn't worked.

I'm wondering if this is intentional or if it's a missing feature? If that's the case can I contribute with a PR to include it?

Thanks!

**Comment by nickpisacane** [comment]
@raerpo  It is definitely not intentional. Will look into it, but PR's are always welcome!

**Comment by raerpo** [comment]
@nickpisacane I would love to help. Will open a PR as soon as I can

**Comment by nickpisacane** [comment]
@raerpo much appreciated!
