### ISSUE TITLE
Swiper init a wrong style in mobile terminal

### ISSUE THREAD

**Issue by manglobe** [nickpisacane/react-dynamic-swiper#7]
![tim 20170717152109](https://user-images.githubusercontent.com/19583202/28258472-ebab1fec-6b03-11e7-8688-051565b62ebc.png)
As you see ,the device width is 320px. But swiper wrapper translate 304px. This problem was also in other width devices. And it just happend after init,and after once touchmove,it works good.

This is my react code  and scss code
![tim 20170717152226](https://user-images.githubusercontent.com/19583202/28258543-5a887ca2-6b04-11e7-9b62-4c812cd0db3e.png)

**Comment by nickpisacane** [comment]
`react-dynamic-swiper` shouldn't have anything to do with that -- it's basically just React "bindings" to the [iDangerous Swiper](https://github.com/nolimits4web/swiper/). I see you are in the Chrome Device Emulator. Is this issue happening when switching between "devices", or on load? Without further information, it's hard to tell if this is a `react-dynamic-swiper` issue, or iDangerous Swiper. Could you post some more code?

**Comment by manglobe** [comment]
@nickpisacane Thank you for reply.
I delete all the other code. This issue is still happened.
This is all my code .  
![tim 20170719091547](https://user-images.githubusercontent.com/19583202/28346842-0d5f2fe4-6c66-11e7-8f29-9888b12e87f9.png)
As you see I used the CSS included with react-dynamic-swiper?

This issue is also happening in Chrome PC devices  and  FireFox .But It works good in IE11.
There was something wrong whis my webpack setting now, I will test it in mobile  later.
Some times ago ,I always used iDangerous Swiper. And I had experienced a Similar problem . And at last I see that's because of the 'padding' and 'box-sizing'. But this time, I never set 'padding' style. 

Thanks for your

**Comment by nickpisacane** [comment]
Any luck? This seems to be something with iDangerous swiper -- the css from `react-dynamic-swiper` is an exact copy from the iDangerous Library (packaged for convenience). I'm going to close for now, but if you find it to be an issue with `react-dynamic-swiper` please re-open. Sorry, this could not be resolved here, and thanks for understanding.
