### ISSUE TITLE
Universal rendering

### ISSUE THREAD

**Issue by vxna** [nickpisacane/react-dynamic-swiper#9]
Hello!

I've allready asked it [here](https://github.com/nolimits4web/Swiper/pull/2123#issuecomment-320067885), and your wrapper seems to be just working out of the box without swiper modifications. 

But it calcuates the wrong sections height on the first render, just the same way. Any ideas?

![2017-08-12_073118](https://user-images.githubusercontent.com/30002276/29237868-43985568-7f30-11e7-96ac-d8cf82993d0b.png)

As I mentioned, it becomes normal after resizing of the page. Thanks!

**Comment by nickpisacane** [comment]
Interesting. Yeah, the point of the [SwiperLib](https://github.com/nickpisacane/react-dynamic-swiper/blob/master/src/SwiperLib.js) wrapper was to allow for SSR (iDangerous-Swiper looks for window and other DOM APIs so can't be loaded in Node without erroring). 

The first thing that comes to mind would be to force iDangerous-Swiper to run its resize/update hooks on mount. The thing that's seems odd, though, is that these should run during initialization. Anyhow, the API for these methods is documented [here](http://idangero.us/swiper/api/#.WY8mZXeGPMU). There are a few ways to access the `swiper` instance from `react-dynamic-swiper` documented [here](https://github.com/nickpisacane/react-dynamic-swiper)  -- particularly calling `.swiper()` on a ref to the `Swiper` component (from `react-dynamic-swiper`) will return the _current_ `iDangerous-Swiper` instance. Invoking `onResize()` or `update()` (or any of the sub-update operations) may be a quick-solve for you. 

It would be nice to know if any of the methods I described above work, but also why the initialization after SSR isn't calculating sizing correctly. The hope of `react-dynamic-swiper` is to support SSR, so I will look into this.

**Comment by nickpisacane** [comment]
I'm having trouble re-creating this issue, SSR seems to be working fine for me. Could you please provide more details on the Swiper options you were using?

**Comment by rahulbasu710** [comment]
Hey guys, I am using this library in production. Does it support universal rendering currently?

**Comment by nickpisacane** [comment]
@rahulbasu710 This library was intended to be used as such. The iDangerous Library (which depends on DOM) is wrapped as to not be loaded in a Node.js (or really, non-DOM) environment. That said, @surepe was having issues which I have not been able to re-create. As you can see, the issue here is technically on the client. Still not positive if this is because of SSR or otherwise. @rahulbasu710, Out of curiosity, have you encountered any issues thus far?

**Comment by rahulbasu710** [comment]
Hey Nick,
 I was using it till now with the swiper init after `componentDidMount` or think of it as showing the Swiper after that as the data was fetched post the mounting. But now I am using API to render the swiper data universally as well. 
I remember there was a problem that the swiper used to be close to each other and after init it used to load it's full functionality like the arrows etc.

I was wondering if that has changed. Also do you mind having a quick chat at Gitter sometime you are free. We can discuss and make it better if there are room for incremental changes.

But the library is awesome as always
Thanks!

**Comment by rahulbasu710** [comment]
Also I recently got stuck with this for some babel problem

`.babelrc`
```
{
  "presets":[
      "env", "react", "stage-0", "es2015"
  ],
   "compact" : true,
  "env": {
    "development": {
      "presets": ["env", "react", "stage-0", "es2015"],
      "plugins": ["transform-runtime", "transform-object-rest-spread"],
      "presets": ["react-hmre"]
    }
  },
  "env": {
    "build": {
      "presets": ["env", "react", "stage-0", "es2015"]
    }
  }
}
```

`terminal error`
```
ERROR in ./node_modules/react-dynamic-swiper/lib/index.js
Module build failed: ReferenceError: Unknown plugin "transform-object-assign" specified in "/Users/rahulbasu/Desktop/repository/beckfriends-heroku/node_modules/react-dynamic-swiper/.babelrc" at 0, attempted to resolve relative to "/Users/rahulbasu/Desktop/repository/beckfriends-heroku/node_modules/react-dynamic-swiper"
    at /Users/rahulbasu/Desktop/repository/beckfriends-heroku/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/rahulbasu/Desktop/repository/beckfriends-heroku/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/rahulbasu/Desktop/repository/beckfriends-heroku/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/rahulbasu/Desktop/repository/beckfriends-heroku/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/rahulbasu/Desktop/repository/beckfriends-heroku/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/rahulbasu/Desktop/repository/beckfriends-heroku/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/rahulbasu/Desktop/repository/beckfriends-heroku/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/rahulbasu/Desktop/repository/beckfriends-heroku/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/rahulbasu/Desktop/repository/beckfriends-heroku/node_modules/babel-loader/lib/index.js:175:20)
 @ ./src/containers/Home/index.js 1:1364-1395
 @ ./src/routes.js
 @ ./src/client.js
 @ multi ./src/client.js
```

**Comment by rahulbasu710** [comment]
Sorry man resolved this. Had to add the `babel-plugin-transform...` in the `.babelrc` and I think it works universally like your demo as of now.

Thanks man!

**Comment by nickpisacane** [comment]
Awesome! Glad you're making use of `react-dynamic-swiper`!
